### ISSUE TITLE
Multiplying intensity by a constant changes the output of spatialDGMM

### ISSUE THREAD

**Issue by mciach** [kuwisdelu/Cardinal#56] opened 2024-12-10 14:47 UTC
Multiplying all intensities in an image by a constant results in a significant change of the segmentation produced by spatialDGMM. 
The same image with all intensities multiplied by 1000 results in a much smoother segmentation.  
This normally shouldn't happen in GMMs, so I suspect either a bug or too harsh constraints on some variance parameters.  
Example to reproduce the issue:

```
## Base image 
mse <- simulateImage(preset=3, dim=c(30,30), npeaks=9, 
                     peakheight=c(3,6,9), centroided=TRUE)

image(mse, i=1:9)
gmm1 <- spatialDGMM(mse, r=2, k=3)
image(gmm1, i=1:9)

## Rescaling the intensity
mse@spectraData$intensity <- 10*mse@spectraData$intensity
image(mse, i=1:9) # Making sure it's the same image as before but with different units of intensity
gmm2 <- spatialDGMM(mse, r=2, k=3)
image(gmm1, i=1:9)
image(gmm2, i=1:9)  # it's smoother than gmm1

## Rescaling the intensity even more
mse@spectraData$intensity <- 100*mse@spectraData$intensity
gmm3 <- spatialDGMM(mse, r=2, k=3)
image(gmm1, i=1:9)
image(gmm2, i=1:9)
image(gmm3, i=1:9)  # different segmentation again
```

image(gmm1, i=1:9):
![image(gmm1, i=1:9)](https://github.com/user-attachments/assets/7f4d148a-a366-4e60-a403-52482a450711)

image(gmm3, i=1:9): 
![image(gmm3, i=1:9)](https://github.com/user-attachments/assets/559c6242-e430-41a4-a0d4-92ceee22a181)

Note the difference in i=3, i=7.

My session info:
```
> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.5 LTS

Matrix products: default
BLAS:   /home/mciach/Programs/R/4.4.1/lib/libRblas.so 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

Random number generation:
 RNG:     L'Ecuyer-CMRG 
 Normal:  Inversion 
 Sample:  Rejection 
 
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=pl_PL.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=pl_PL.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Warsaw
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Cardinal_3.8.0      S4Vectors_0.44.0    ProtGenerics_1.38.0 BiocGenerics_0.52.0
[5] BiocParallel_1.40.0

loaded via a namespace (and not attached):
 [1] knitr_1.49         nlme_3.1-166       cli_3.6.3          xfun_0.49         
 [5] rlang_1.1.4        tiff_0.1-12        png_0.1-8          RCurl_1.98-1.16   
 [9] htmltools_0.5.8.1  ontologyIndex_2.12 rmarkdown_2.29     Biobase_2.66.0    
[13] locfit_1.5-9.10    grid_4.4.1         evaluate_1.0.1     abind_1.4-8       
[17] bitops_1.0-9       fastmap_1.2.0      yaml_2.3.10        compiler_4.4.1    
[21] codetools_0.2-20   CardinalIO_1.4.0   irlba_2.3.5.1      htmlwidgets_1.6.4 
[25] fftwtools_0.9-11   EBImage_4.48.0     lattice_0.22-6     digest_0.6.37     
[29] matter_2.8.0       parallel_4.4.1     Matrix_1.7-1       tools_4.4.1       
[33] jpeg_0.1-10       
```

**Comment by kuwisdelu** [comment] 2024-12-10 20:52
I'm closing this as a duplicate of kuwisdelu/matter#41 as the root cause is the same -- if you want to add more reproducible examples on `spatialDGMM` smoothing behavior (which is appreciated), please do so on that issue. Thanks.

**Closed as not planned by kuwisdelu** 2024-12-10 20:52 UTC
